version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pralish
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: pralish/rails_project
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://pralish:password@db:5432/db
    depends_on:
      - db
volumes:
  pgdata:
